model_name: BSC-LT/salamandra-7b-instruct
eos_token: </s>
words: data/CREA_10k-v2/4-CREA_10k_lemmas.tsv
iter: promptV8-no-fs
prompts: prompts/no_cat/llama/v8.json
num_words: 4594
categories: False
batch_size_def: 8
batch_size_words: 16
