model_name: mistralai/Mistral-7B-Instruct-v0.1
eos_token: </s>
words: data/DEA_100/100_palabras_DEA_v5.tsv
iter: promptV8-no-fs
prompts: prompts/no_cat/mistral/v8.json
num_words: 4594
categories: False
batch_size_def: 4
batch_size_words: 8
