model_name: bertin-project/Gromenauer-7B-Instruct
eos_token: </s>
words: data/DEA_100/100_palabras_DEA_v5.tsv
iter: promptV8-no-fs
prompts: prompts/no_cat/llama/v8.json
num_words: 4594
categories: False
batch_size_def: 8
batch_size_words: 16
